### ISSUE TITLE
Flutter Driver vs Widget Test vs Unit Test

### ISSUE THREAD

**Issue by HerrNiklasRaab** [Polidea/blemulator_flutter#109]
Hey,

just wondering if this can only be used in Flutter Integration Tests (Flutter Driver) or also in Widget and Unit Tests?

Best,

Niklas

**Comment by HerrNiklasRaab** [comment]
Because I get this message, when I try it in a Unit Test:

> MissingPluginException(No implementation found for method simulate on channel com.polidea.blemulator/toJava)
> package:flutter/src/services/platform_channel.dart 154:7  MethodChannel._invokeMethod

**Comment by mikolak** [comment]
Hi!

I'm afraid simulation is plugged in inside the native code, so it won't work in widget/unit tests. As a side note I think you'd be better off abstracting the peripheral logic away from widgets and mocking anything BLE related in unit tests.
