### ISSUE TITLE
iOS App crashes with NSInvalidArgumentException when passing an manufacturer data to a simulated peripheral

### ISSUE THREAD

**Issue by Smibser** [Polidea/blemulator_flutter#123]
When I am setting the manufactorData in the scanInfo of a SimulatedPeripheral, the whole app crashes as soon as the scanning is started. This only happens on iOS, on android it works as expected. Here is the ios crash report:

[Runner_2020-11-25-091822_gs-MacBook-Pro.txt](https://github.com/Polidea/blemulator_flutter/files/5595602/Runner_2020-11-25-091822_gs-MacBook-Pro.txt)

**Comment by mikolak** [comment]
Fixed in 1.2.1
